APP-92 Fixed the access_checker.py, warcserver.py
mirrorweb/pywb pull request #2
Opened 2021-04-21 16:21 UTC by omerijaz27

2021-04-23 15:32 UTC, mijho reviewed
@omerijaz27 it's probably better to get either @Leeeebs or @mdncs to take a look over the python side.

I'd also remove the wombat submodule from the commit.

2021-04-27 08:59 UTC, Leeeebs requested changes
Need to remove the wombat stuff - but should be fine to release for testing

2021-04-27 08:59 UTC, Leeeebs commented on pywb/warcserver/access_checker.py
> +                }, url=url)
just a note, this doesn't take into account dates.

2021-04-30 10:02 UTC, omgoo requested changes
Now merged to TNA branch

2021-05-05 09:38 UTC, closed without merging